spring:
  profiles:
    active:
      - dev

--- 
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver              
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false             
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.atguigu.springcloud.entities    
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       

eureka:
  instance:
    prefer-ip-address: true   #注册服务使用服务的ip地址
    instance-id: microservicecloud-dept8001
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
--- 
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver              
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false             
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.atguigu.springcloud.entities    
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       

eureka:
  instance:
    prefer-ip-address: true   #注册服务使用服务的ip地址
    instance-id: microservicecloud-dept8001
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@